config/routes.rb
BobtailApp::Application.routes.draw do

  root "static_pages#home"

  resources :admins
  resources :sessions, only: [:create]
  resources :news_items, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :shows_items, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :projects
  resources :albums
  resources :songs

  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"

  match "/lyrics", to: "static_pages#lyrics", via: "get"

end

app/views/admins/_form.html.erb
<% if @admin.errors.any? %>
  <ul id="errors">
    <% @admin.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @admin do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "part-width" %>
  </div>

  <% if (current_admin.super_admin && !@admin.super_admin) ||
    @admin == current_admin %>
  <div>
    <%= f.label :password %>
    <span class="small_text">(when updating, can be left blank)</span><br>
    <%= f.password_field :password, class: "part-width" %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "part-width" %>
  </div>
  <% end %>

  <div>
    <%= f.label :description, "Description for band page" %>
    <span class="small_text">(optional, html-friendly)</span><br>
    <%= f.text_area :description, class: "full-width" %>
  </div>
  <% if params[:preview] %>
    Preview description:
    <div id="preview_text">
      <%= @admin.description.html_safe %>
    </div>
  <% end %>

  <% if current_admin.super_admin &&
    (@admin == current_admin || !@admin.super_admin) %>
  <div>
    <%= f.label :super_admin %>
    <%= f.check_box :super_admin %>
    <span class="small_text">(this cannot be undone by you!)</span><br>
  </div>
  <% end %>

  <%= f.submit "Cancel", name: "cancel" %>
  <%= f.submit "Preview description", name: "preview" %>
  <%= f.submit %>
<% end %>

app/views/admins/edit.html.erb
<div id="single_content">
  <div id="admin_content">
    <h1>Update <%= @admin.name %>'s info</h1>
    <%= render "form" %>
  </div>
</div>

app/views/admins/index.html.erb
<div id="single_content">
  <div id="admin_content">
    <% if current_admin.super_admin %>
      <%= link_to "Create a new admin", new_admin_path %>
    <% end %>
    <table>
      <thead>
        <th colspan="3"><h1>List of admins</h1></th>
      </thead>
      <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td>
          <% if admin.super_admin %>
            super admin
          <% else %>
            bandmate
          <% end %>
        </td>
        <% if admin == current_admin ||
          current_admin.super_admin %>
          <td ><%= link_to "update", edit_admin_path(admin) %> |
            <%= link_to "delete", admin_path(admin), method: :delete,
            data: { confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admins/new.html.erb
<div id="single_content">
  <div id="admin_content">
    <h1>Create a new admin</h1>
    <%= render "form" %>
  </div>
</div>

app/views/admins/show.html.erb
<%= render "projects/sidebar" %>

<div id="main_content">

  <h1>Meet <%= @admin.name %></h1>
  <div id="text_description">
    <%= @admin.description.html_safe if @admin.description.present? %>
  </div>

  <% if current_admin? && (@admin == current_admin || current_admin.super_admin) %>
    <div id="admin_span">
      <span><%= link_to "Update info", edit_admin_path %></span>
    </div>
  <% end %>
  <% if current_admin? && @admin == current_admin %>
    <div id="admin_span">
      <span><%= link_to "Create a new project", new_project_path %></span>
    </div>
  <% end %>

</div>