config/routes.rb
BobtailApp::Application.routes.draw do

  root "static_pages#home"

  resources :admins
  resources :sessions, only: [:create]
  resources :news_items, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :shows_items, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :projects
  resources :albums
  resources :songs

  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"

  match "/lyrics", to: "static_pages#lyrics", via: "get"

end

app/models/shows_item.rb
class ShowsItem < ActiveRecord::Base

  before_validation :smart_add_url_protocol

  paginates_per 15
  validates_presence_of :name, :city, :state

  protected

  def smart_add_url_protocol
    if self.webpage.present?
      unless self.webpage == "" || self.webpage[/^http:\/\//] ||
        self.webpage[/^https:\/\//]
        self.webpage = 'http://' + self.webpage
      end
    end
  end

end

app/controllers/shows_items_controller.rb
class ShowsItemsController < ApplicationController

  before_action :admin_logged_in!, except: [:index]
  before_action :store_location, except: [:new, :edit, :update]

  def index
    @shows_page = true # for displaying proper header buttons
    @upcoming_shows = ShowsItem.where(["date >= ?",
      Time.now]).order("date")
    @past_shows = ShowsItem.where(["date <= ?",
      Time.now]).order("date DESC").page params[:page]
  end

  def new
    @shows_item = ShowsItem.new
  end

  def edit
    @shows_item = ShowsItem.find(params[:id])
  end

  def create
    @shows_item = ShowsItem.new(shows_items_params)
    if params[:cancel]
      redirect_back_or(shows_items_url)
    elsif @shows_item.save
      flash[:notice] = "Show posted."
      redirect_to shows_items_url
    else
      render "new"
    end
  end

  def update
    @shows_item= ShowsItem.find(params[:id])
    if params[:cancel]
      redirect_back_or(shows_items_url)
    elsif @shows_item.update(shows_items_params)
      flash[:notice] = "Show updated."
      redirect_to shows_items_url
    else
      render "edit"
    end
  end

  def destroy
    @shows_item = ShowsItem.find(params[:id])
    @shows_item.destroy
    flash[:notice] = "Show deleted."
    redirect_to shows_items_url
  end

  private

  def shows_items_params
    params.require(:shows_item).
      permit(:name, :webpage, :city, :state, :extra, :date)
  end

end

app/helpers/shows_items_helper.rb
module ShowsItemsHelper
end

app/views/shows_items/_form.html.erb
<% if @shows_item.errors.any? %>
  <ul id="errors">
    <% @shows_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @shows_item do |f| %>
  <div>
    <%= f.label :name, "Venue name" %><br>
    <%= f.text_field :name, class: "full-width" %>
  </div>
  <div>
    <%= f.label :webpage, "Venue webpage" %>
    <span class="small_text">(optional)</span><br>
    <%= f.text_field :webpage, class: "full-width" %>
  </div>
  <div>
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "part-width" %>
  </div>
  <div>
    <%= f.label :state, "State or Country" %><br>
    <%= f.text_field :state, class: "part-width" %>
  </div>
  <div>
    <%= f.label :date, "Date and Time" %><br>
    <%= f.datetime_select :date, default: Time.now.at_end_of_day - 2.hours,
      ampm: true, minute_step: 15 %>
  </div>
  <div>
    <%= f.label :extra, "Any extra info" %>
    <span class="small_text">(optional, please keep it minimal)</span><br>
    <%= f.text_field :extra, class: "full-width" %>
  </div>
  <%= f.submit "Cancel", name: "cancel" %>
  <%= f.submit %>
<% end %>

app/views/shows_items/edit.html.erb
<div id="single_content">
  <div id="admin_content">
    <h1>Update this show</h1>
    <%= render "form" %>
  </div>
</div>

app/views/shows_items/index.html.erb
<% if current_admin? %>
  <div id="admin_span">
    <span><%= link_to "Post a show", new_shows_item_path %></span>
  </div>
<% end %>
<h1>Upcoming shows</h1>
<table>
  <% if @upcoming_shows.empty? %>
    <tr>
      <td>No upcoming shows scheduled.</td>
    </tr>
  <% else %>
    <% @upcoming_shows.each do |shows_item| %>
      <tr>
      <% if shows_item.webpage.present? %>
        <td><%= link_to shows_item.name, shows_item.webpage, target: "_blank" %></td>
      <% else %>
        <td><%= shows_item.name %></td>
      <% end %>
      <td><%= shows_item.city %>, <%= shows_item.state %></td>
      <td><%= shows_item.date.strftime("%b %d at %-I:%M%P") %></td>
      <td><%= shows_item.extra %></td>
        <% if current_admin? %>
        <td id="admin_links">
          <%= link_to "update", edit_shows_item_path(shows_item) %> |
          <%= link_to "delete", shows_item_path(shows_item),
            method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      <% end %>
      </tr>
    <% end %>
  <% end %>
</table><br/>

<h3>Past shows</h3>
<table>
  <% @past_shows.each do |shows_item| %>
    <tr>
    <% if shows_item.webpage.present? %>
      <td><%= link_to shows_item.name, shows_item.webpage, target: "_blank" %></td>
    <% else %>
      <td><%= shows_item.name %></td>
    <% end %>
    <td><%= shows_item.city %>, <%= shows_item.state %></td>
    <td><%= shows_item.date.strftime("%b %d %Y") %></td>
      <% if current_admin? %>
      <td id="admin_links">
        <%= link_to "update", edit_shows_item_path(shows_item) %> |
        <%= link_to "delete", shows_item_path(shows_item),
          method: :delete, data: { confirm: "Are you sure?" } %>
      </td>
    <% end %>
    </tr>
  <% end %>
</table>
<%= paginate @past_shows %>

app/views/shows_items/new.html.erb
<div id="single_content">
  <div id="admin_content">
    <h1>Post a new show</h1>
    <%= render "form" %>
  </div>
</div>