config/routes.rb
BobtailApp::Application.routes.draw do

  root "static_pages#home"

  resources :admins
  resources :sessions, only: [:create]
  resources :news_items, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :shows_items, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :projects
  resources :albums
  resources :songs

  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"

  match "/lyrics", to: "static_pages#lyrics", via: "get"

end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  belongs_to :admin
  validates :heading, length: { minimum: 3 }
  validates :entry, length: { minimum: 10 }

  paginates_per 5
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController

  before_action :admin_logged_in!, except: [:index]
  before_action :store_location, except: [:new, :edit, :update]

  def index
    @news_page = true # for displaying proper header buttons
    @news_items = NewsItem.order("created_at DESC").page params[:page]
  end

  def new
    @news_item = NewsItem.new
  end

  def edit
    @news_item = NewsItem.find(params[:id])
  end

  def create
    @news_item = NewsItem.new(news_items_params)
    @news_item.admin_name = current_admin.name
    # admin name for news item will persist even if admin is later deleted
    if params[:cancel]
      redirect_back_or(news_items_url)
    elsif params[:preview]
      temp_preview_changes
      render "new"
    elsif @news_item.save
      flash[:notice] = "News item posted."
      redirect_to news_items_url
    else
      render "new"
    end
  end

  def update
    @news_item= NewsItem.find(params[:id])
    if params[:cancel]
      redirect_back_or(news_items_url)
    elsif params[:preview]
      temp_preview_changes
      render "edit"
    elsif @news_item.update(news_items_params)
      flash[:notice] = "News item updated."
      redirect_to news_items_url
    else
      render "edit"
    end
  end

  def destroy
    @news_item = NewsItem.find(params[:id])
    @news_item.destroy
    flash[:notice] = "News item deleted."
    redirect_to news_items_url
  end

  private

  def news_items_params
    params.require(:news_item).permit(:heading, :entry)
  end

  def temp_preview_changes
    @news_item[:heading] = params[:news_item][:heading]
    @news_item[:entry] = params[:news_item][:entry]
  end

end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/views/news_items/_form.html.erb
<% if @news_item.errors.any? %>
  <ul id="errors">
    <% @news_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @news_item do |f| %>
  <div>
    <%= f.label :heading %>
    <span class="small_text">(html-friendly)</span><br>
    <%= f.text_field :heading, class: "full-width" %>
  </div>
  <div>
    <%= f.label :entry %>
    <span class="small_text">(html-friendly)</span><br>
    <%= f.text_area :entry, class: "full-width" %>
  </div>
  <% if params[:preview] %>
    Preview:
    <h3><%= @news_item.heading.html_safe %></h3>
    <div id="preview_text"><%= @news_item.entry.html_safe %></div>
  <% end %>
  <%= f.submit "Cancel", name: "cancel" %>
  <%= f.submit "Preview", name: "preview" %>
  <%= f.submit %>
<% end %>

app/views/news_items/edit.html.erb
<div id="single_content">
  <div id="admin_content">
    <h1>Update this news item</h1>
    <%= render "form" %>
  </div>
</div>

app/views/news_items/index.html.erb
<div id="single_content">

  <% if current_admin? %>
    <div id="admin_span">
      <span><%= link_to "Post a news item", new_news_item_path %></span>
    </div>
  <% end %>

  <% @news_items.each do |news_item| %>
    <div class="news_item">
      <h3><%= news_item.heading.html_safe %></h3>
      <h6>Posted by <%= news_item.admin_name %>
        <%= news_item.created_at.in_time_zone("Pacific Time (US & Canada)").
        strftime("on %b %d %Y at %-I:%M%P") %></h6>
      <div class="news_entry"><%= news_item.entry.html_safe %></div>
      <% if current_admin? %>
        <div>
          <span id="admin_links"><%= link_to "update", edit_news_item_path(news_item) %> |
          <%= link_to "delete", news_item_path(news_item),
            method: :delete, data: { confirm: "Are you sure?" } %></span>
        </div>
      <% end %>
    </div>
  <% end %>
<%= paginate @news_items %>
</div>

app/views/news_items/new.html.erb
<div id="single_content">
  <div id="admin_content">
    <h1>Post a news item</h1>
    <%= render "form" %>
  </div>
</div>