config/routes.rb
BobtailApp::Application.routes.draw do

  root "static_pages#home"

  resources :admins
  resources :sessions, only: [:create]
  resources :news_items, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :shows_items, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :projects
  resources :albums
  resources :songs

  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"

  match "/lyrics", to: "static_pages#lyrics", via: "get"

end

app/views/layouts/_footer.html.erb
<footer>
  <div id="copyright">
    &copy;2014 Bobtail Yearlings
    <h6>Website by Bennett using Ruby on Rails!</h6>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>

  <% if current_admin.present? %>
  <div id="admin_logged">
    <span>
      Howdy, <%= current_admin.name %>!
        | <%= link_to "Admins page", admins_path %>
        | <%= link_to "Albums page", albums_path %>
        | <%= link_to "Logout", logout_path %>
    </span>
  </div>
  <% elsif !Rails.env.production? %>
  <div id="admin_logged">
    <span>
      <%= link_to "Register", new_admin_path %>
        | <%= link_to "Login", login_path %>
   </span>
  </div>
  <% end %>



  <div id="title_logo">
    <%= link_to image_tag("bobtail_b.gif"), root_path %>
  </div>
  <ul id="menu_buttons"><h2>

    <% if @songs_page %>
      <li class="picked_heading">Music</li>
      <% else %>
      <li><%= link_to "Music", songs_path %></li>
    <% end %>

    <% if @projects_page %>
      <li class="picked_heading">Band</li>
      <% else %>
      <li><%= link_to "Band", projects_path %></li>
    <% end %>

    <% if @shows_page %>
      <li class="picked_heading">Shows</li>
      <% else %>
      <li><%= link_to "Shows", shows_items_path %></li>
    <% end %>

    <% if @news_page %>
      <li class="picked_heading">News</li>
      <% else %>
      <li><%= link_to "News", news_items_path %></li>
    <% end %>

  </h2></ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BobtailApp</title>
  <link href='http://fonts.googleapis.com/css?family=Rancho|Fresca' rel='stylesheet'>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <%= render "layouts/header" %>
    <div id="content">
      <div id="notice"><%= notice %></div>
      <div id="alert"><%= alert %></div>
      <%= yield %>
    </div>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>